apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: backend 
  namespace: expense01
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
  namespace: expense01
  labels:
    app: backend
    tier: api 
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api 
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: srinikysj4512/backend:v1
        envFrom:
          - configMapRef:
              name: backend
---
apiVersion: v1 
kind: Service 
metadata:
  name: backend
  namespace: expense01 
spec: 
  selector: 
    app: backend
    tier: api
    project: expense 
  ports: 
    - name: backend-port
      protocol: TCP 
      port: 8080 # service port 
      targetPort: 8080 # container port
